### ISSUE TITLE
Mesh/Model Viewer Property Grid

### ISSUE THREAD

**Issue by jessaskey** [manfreda-dot-org/I-Robot-Editor#1]
Not sure what your thoughts are on external dependencies since the current project is pristine. 

This might be a great candidate... https://github.com/xceedsoftware/wpftoolkit  ...although it does have it's own license agreement.

I would be willing to code this into the right side of the MeshViewer.DockPanel and create a pull request to you if you are interested. I was thinking of adding an SVG export button as well easy extraction (future additions?).

**Comment by manfreda-dot-org** [comment]
Hey Jess sorry I haven't gotten back to you right away
Not blowing you off, I'm out at winter testing and the days are long and
I've just not had time to go through personal emails
I'll get back to you when I get back next week
In the meantime do whatever you want with the code, personally if you think
the codebase is better I have no problem merging into mainline

**Comment by jessaskey** [comment]
Ah.. nah, not a big deal at all… I have the objects all exported but don’t know that I will actually have time to implement enough 16-bit routines before I get this out in Havoc, but we will see how it goes. I think your code is great, I just modified it to easily export all the main object models out and so I don’t really see a good reason to commit that to what you have… I will check back with ya later this spring tho!!!  Talk to you later.  Jess

**Comment by jessaskey** [comment]
PS….   Stay warm up there!!!
